export enum ApiEntityListTypeEnum {
  CHILD_ROWS = 'childRows',
  LIST = 'list',
  DATE = 'date',
  DATETIME = 'datetime',
  PERCENT = 'percent',
  BOOLEAN = 'boolean',
  DATETIME_BOOLEAN = 'datetime-boolean',
  DATETIME_RANGE = 'datetime-range',
  DATETIME_RANGE_BOOLEAN = 'datetime-range-boolean',
  URL = 'url',
  EMAIL = 'email',
  PHONE = 'phone',
  NUMBER = 'number',
}
